import type { Product } from "@/types";
import { img } from "../../src/lib/images";

const APPAREL_SIZES = ["XS", "S", "M", "L", "XL"];
const SHOE_SIZES = ["7", "8", "9", "10", "11", "12"];
const ONE_SIZE = ["One Size"];

/**
 * The starting catalogue.
 *
 * This is seed material, not runtime data — the shop reads products from
 * Postgres. Appending here changes nothing until `npm run db:seed` runs, and
 * seeding only replaces rows marked `source: "seed"`, so an operator's imported
 * products are never touched.
 */
export const products: Product[] = [
  {
    id: "1001",
    name: "Essential Cotton Tee",
    slug: "essential-cotton-tee",
    category: "men",
    price: 38,
    originalPrice: 52,
    rating: 4.7,
    reviewCount: 214,
    images: [
      img("photo-1521572163474-6864f9cf17ab"),
      img("photo-1581655353564-df123a1eb820"),
      img("photo-1571945153237-4929e783af4a"),
    ],
    description:
      "The tee we rebuilt four times before we were happy with it. Long-staple Supima cotton is knitted to a 180gsm weight that holds its shape through repeated washing, with a ribbed collar that refuses to stretch out.",
    details: [
      "180gsm long-staple Supima cotton",
      "Self-fabric ribbed collar with taped shoulder seams",
      "Pre-shrunk and garment washed",
      "Machine wash cold, tumble dry low",
    ],
    specifications: {
      Material: "100% Supima cotton",
      Weight: "180 gsm",
      Fit: "Regular",
      Origin: "Made in Portugal",
      Care: "Machine wash cold",
    },
    sizes: APPAREL_SIZES,
    colors: [
      { name: "White", hex: "#f7f6f3" },
      { name: "Black", hex: "#1b1b1b" },
      { name: "Clay", hex: "#b1795d" },
    ],
    tags: ["cotton", "basics", "everyday"],
    featured: true,
    inStock: true,
  },
  {
    id: "1002",
    name: "Heavyweight Crew Sweatshirt",
    slug: "heavyweight-crew-sweatshirt",
    category: "men",
    price: 96,
    rating: 4.8,
    reviewCount: 138,
    images: [
      img("photo-1620799140408-edc6dcb6d633"),
      img("photo-1620799140188-3b2a02fd9a77"),
      img("photo-1523381210434-271e8be1f52b"),
    ],
    description:
      "A 420gsm loopback fleece with a dense hand-feel that softens rather than pills. Cut with a slightly dropped shoulder so it layers cleanly over a tee without bunching.",
    details: [
      "420gsm loopback cotton fleece",
      "Dropped shoulder, relaxed body",
      "Ribbed cuffs and hem with elastane for recovery",
    ],
    specifications: {
      Material: "80% cotton, 20% recycled polyester",
      Weight: "420 gsm",
      Fit: "Relaxed",
      Origin: "Made in Portugal",
      Care: "Machine wash cold, dry flat",
    },
    sizes: APPAREL_SIZES,
    colors: [
      { name: "Bone", hex: "#efece5" },
      { name: "Charcoal", hex: "#3c3c3c" },
    ],
    tags: ["fleece", "layering"],
    featured: true,
    inStock: true,
  },
  {
    id: "1003",
    name: "Rider Leather Jacket",
    slug: "rider-leather-jacket",
    category: "men",
    price: 448,
    originalPrice: 560,
    rating: 4.9,
    reviewCount: 64,
    images: [
      img("photo-1487222477894-8943e31ef7b2"),
      img("photo-1551028719-00167b16eac5"),
      img("photo-1591047139829-d91aecb6caea"),
    ],
    description:
      "Full-grain lambskin with an asymmetric zip and a collar that sits flat when open. It arrives stiff by design and moulds to you over the first season.",
    details: [
      "Full-grain lambskin, vegetable tanned",
      "Antique brass hardware",
      "Cupro lining with two interior pockets",
    ],
    specifications: {
      Material: "100% lambskin leather",
      Lining: "Cupro",
      Fit: "Slim",
      Origin: "Made in Spain",
      Care: "Professional leather clean only",
    },
    sizes: APPAREL_SIZES,
    colors: [
      { name: "Tobacco", hex: "#7a4a2b" },
      { name: "Black", hex: "#181818" },
    ],
    tags: ["leather", "outerwear", "premium"],
    featured: true,
    inStock: true,
  },
  {
    id: "1004",
    name: "Chambray Utility Shirt",
    slug: "chambray-utility-shirt",
    category: "men",
    price: 118,
    rating: 4.5,
    reviewCount: 91,
    images: [
      img("photo-1596755094514-f87e34085b2c"),
      img("photo-1523381210434-271e8be1f52b"),
      img("photo-1593030761757-71fae45fa0e7"),
    ],
    description:
      "Woven from a soft Japanese chambray that fades along the seams the way good denim does. Two chest pockets, a single-needle placket and corozo buttons.",
    details: [
      "Japanese 5oz chambray",
      "Corozo nut buttons",
      "Single-needle placket and side seams",
    ],
    specifications: {
      Material: "100% cotton chambray",
      Weight: "5 oz",
      Fit: "Regular",
      Origin: "Made in Japan",
      Care: "Machine wash cold, iron warm",
    },
    sizes: APPAREL_SIZES,
    colors: [
      { name: "Indigo", hex: "#4a6079" },
      { name: "Sage", hex: "#7f8d78" },
    ],
    tags: ["shirt", "cotton"],
    inStock: true,
  },
  {
    id: "1005",
    name: "Terracotta Bomber Jacket",
    slug: "terracotta-bomber-jacket",
    category: "men",
    price: 210,
    originalPrice: 265,
    rating: 4.6,
    reviewCount: 47,
    images: [
      img("photo-1591047139829-d91aecb6caea"),
      img("photo-1551028719-00167b16eac5"),
      img("photo-1487222477894-8943e31ef7b2"),
    ],
    description:
      "A featherweight bomber in technical nylon with a matte finish. Water-repellent, packable, and cut short enough to wear over a knit.",
    details: [
      "Recycled ripstop nylon with DWR finish",
      "Ribbed collar, cuffs and hem",
      "Packs into its own interior pocket",
    ],
    specifications: {
      Material: "100% recycled nylon",
      Finish: "PFC-free DWR",
      Fit: "Regular",
      Origin: "Made in Vietnam",
      Care: "Machine wash cold, do not iron",
    },
    sizes: APPAREL_SIZES,
    colors: [
      { name: "Terracotta", hex: "#c06a49" },
      { name: "Olive", hex: "#5f6448" },
    ],
    tags: ["outerwear", "lightweight"],
    newArrival: true,
    inStock: true,
  },
  {
    id: "1006",
    name: "Poplin Dress Shirt",
    slug: "poplin-dress-shirt",
    category: "men",
    price: 128,
    rating: 4.4,
    reviewCount: 73,
    images: [
      img("photo-1598032895397-b9472444bf93"),
      img("photo-1617137968427-85924c800a22"),
      img("photo-1593030761757-71fae45fa0e7"),
    ],
    description:
      "Crisp two-ply poplin with a semi-spread collar that holds its line without fusing. Cut close through the body but generous across the back.",
    details: [
      "Two-ply 120s Italian poplin",
      "Semi-spread collar, unfused construction",
      "Mother-of-pearl buttons",
    ],
    specifications: {
      Material: "100% Egyptian cotton",
      Collar: "Semi-spread",
      Fit: "Slim",
      Origin: "Made in Italy",
      Care: "Machine wash cold, iron hot",
    },
    sizes: APPAREL_SIZES,
    colors: [
      { name: "White", hex: "#f8f8f6" },
      { name: "Pale Blue", hex: "#c5d5e4" },
      { name: "Lilac", hex: "#cfc4dd" },
    ],
    tags: ["shirt", "formal"],
    inStock: true,
  },
  {
    id: "1007",
    name: "Slim Navy Blazer",
    slug: "slim-navy-blazer",
    category: "men",
    price: 385,
    rating: 4.7,
    reviewCount: 38,
    images: [
      img("photo-1617137968427-85924c800a22"),
      img("photo-1593030761757-71fae45fa0e7"),
      img("photo-1598032895397-b9472444bf93"),
    ],
    description:
      "A half-lined travel blazer in a high-twist wool that shrugs off creases. Soft shoulder, patch pockets, and enough give to wear all day.",
    details: [
      "High-twist Italian wool, 250gsm",
      "Half-canvassed with a soft Neapolitan shoulder",
      "Patch pockets and functional cuff buttons",
    ],
    specifications: {
      Material: "100% wool",
      Weight: "250 gsm",
      Fit: "Slim",
      Origin: "Made in Italy",
      Care: "Dry clean only",
    },
    sizes: APPAREL_SIZES,
    colors: [{ name: "Navy", hex: "#22314f" }],
    tags: ["tailoring", "wool", "premium"],
    inStock: false,
  },
  {
    id: "1008",
    name: "Graphic Print Tee",
    slug: "graphic-print-tee",
    category: "men",
    price: 45,
    rating: 4.2,
    reviewCount: 156,
    images: [
      img("photo-1503341504253-dff4815485f1"),
      img("photo-1576566588028-4147f3842f27"),
      img("photo-1618354691373-d851c5c3a990"),
    ],
    description:
      "Water-based discharge print on a washed cotton body, so the graphic sits in the fabric rather than on top of it. It will crack a little. That is the point.",
    details: [
      "Water-based discharge print",
      "Garment-dyed and enzyme washed",
      "Longline body with a curved hem",
    ],
    specifications: {
      Material: "100% combed cotton",
      Weight: "160 gsm",
      Fit: "Longline",
      Origin: "Made in Portugal",
      Care: "Wash inside out, cold",
    },
    sizes: APPAREL_SIZES,
    colors: [
      { name: "Black", hex: "#1a1a1a" },
      { name: "Sand", hex: "#ded3c2" },
    ],
    tags: ["print", "cotton"],
    inStock: true,
  },
  {
    id: "1009",
    name: "Suede Derby Shoe",
    slug: "suede-derby-shoe",
    category: "men",
    price: 245,
    originalPrice: 290,
    rating: 4.6,
    reviewCount: 52,
    images: [
      img("photo-1560343090-f0409e92791a"),
      img("photo-1549298916-b41d501d3772"),
      img("photo-1593030761757-71fae45fa0e7"),
    ],
    description:
      "An open-laced derby in Italian calf suede on a lightweight rubber sole. Dressy enough for the office, soft enough to walk the long way home.",
    details: [
      "Italian calf suede upper",
      "Blake-stitched construction",
      "Lightweight moulded rubber sole",
    ],
    specifications: {
      Material: "Calf suede",
      Sole: "Rubber",
      Construction: "Blake stitch",
      Origin: "Made in Italy",
      Care: "Brush with a suede brush",
    },
    sizes: SHOE_SIZES,
    colors: [
      { name: "Teal", hex: "#2f6f6b" },
      { name: "Sand", hex: "#c8ab84" },
    ],
    tags: ["footwear", "suede"],
    newArrival: true,
    inStock: true,
  },
  {
    id: "1010",
    name: "Court Suede Sneaker",
    slug: "court-suede-sneaker",
    category: "men",
    price: 165,
    rating: 4.5,
    reviewCount: 187,
    images: [
      img("photo-1549298916-b41d501d3772"),
      img("photo-1460353581641-37baddab0fa2"),
      img("photo-1560769629-975ec94e6a86"),
    ],
    description:
      "A low-profile court sneaker with a nubuck upper and a cupsole that stays white longer than it has any right to.",
    details: [
      "Nubuck leather upper",
      "Vulcanised rubber cupsole",
      "Moulded EVA footbed",
    ],
    specifications: {
      Material: "Nubuck leather",
      Sole: "Vulcanised rubber",
      Fit: "True to size",
      Origin: "Made in Portugal",
      Care: "Spot clean",
    },
    sizes: SHOE_SIZES,
    colors: [
      { name: "Tan", hex: "#b07f4f" },
      { name: "White", hex: "#f2f0eb" },
    ],
    tags: ["footwear", "sneaker"],
    featured: true,
    inStock: true,
  },
  {
    id: "1011",
    name: "Trail Runner",
    slug: "trail-runner",
    category: "men",
    price: 140,
    originalPrice: 185,
    rating: 4.3,
    reviewCount: 96,
    images: [
      img("photo-1542291026-7eec264c27ff"),
      img("photo-1600185365483-26d7a4cc7519"),
      img("photo-1460353581641-37baddab0fa2"),
    ],
    description:
      "A cushioned runner built on a rockered foam midsole, with an engineered knit upper that breathes on the climb and holds on the descent.",
    details: [
      "Engineered knit upper",
      "Rockered supercritical foam midsole",
      "4mm lugged outsole",
    ],
    specifications: {
      Material: "Engineered knit",
      Drop: "8 mm",
      Weight: "268 g (US 9)",
      Origin: "Made in Vietnam",
      Care: "Air dry only",
    },
    sizes: SHOE_SIZES,
    colors: [
      { name: "Ember", hex: "#c0392b" },
      { name: "Slate", hex: "#5a6470" },
    ],
    tags: ["footwear", "performance"],
    inStock: true,
  },
  {
    id: "1012",
    name: "Air Knit Sneaker",
    slug: "air-knit-sneaker",
    category: "men",
    price: 155,
    rating: 4.4,
    reviewCount: 131,
    images: [
      img("photo-1600185365483-26d7a4cc7519"),
      img("photo-1460353581641-37baddab0fa2"),
      img("photo-1542291026-7eec264c27ff"),
    ],
    description:
      "An everyday trainer with a visible air unit and a knit collar that slips on without fuss. Neutral enough to wear with tailoring.",
    details: [
      "Breathable knit upper with synthetic overlays",
      "Visible air cushioning unit",
      "Padded knit collar",
    ],
    specifications: {
      Material: "Knit and synthetic",
      Sole: "Rubber",
      Fit: "True to size",
      Origin: "Made in Vietnam",
      Care: "Spot clean",
    },
    sizes: SHOE_SIZES,
    colors: [
      { name: "Bone", hex: "#e9e5dd" },
      { name: "Grey", hex: "#9aa0a6" },
    ],
    tags: ["footwear", "sneaker"],
    newArrival: true,
    inStock: true,
  },
  {
    id: "2001",
    name: "Wool Overcoat",
    slug: "wool-overcoat",
    category: "women",
    price: 420,
    originalPrice: 520,
    rating: 4.8,
    reviewCount: 86,
    images: [
      img("photo-1483985988355-763728e1935b"),
      img("photo-1515886657613-9f3515b0c78f"),
      img("photo-1490481651871-ab68de25d43d"),
    ],
    description:
      "A double-faced wool coat with a shawl collar that stands up against the wind. Cut long and lean, with deep welt pockets you can actually use.",
    details: [
      "Double-faced Italian wool and cashmere",
      "Hand-finished shawl collar",
      "Deep welt pockets, unlined body",
    ],
    specifications: {
      Material: "90% wool, 10% cashmere",
      Length: "108 cm (size S)",
      Fit: "Relaxed",
      Origin: "Made in Italy",
      Care: "Dry clean only",
    },
    sizes: APPAREL_SIZES,
    colors: [
      { name: "Burgundy", hex: "#6d2434" },
      { name: "Camel", hex: "#b4895c" },
    ],
    tags: ["outerwear", "wool", "premium"],
    featured: true,
    inStock: true,
  },
  {
    id: "2002",
    name: "Fringed Knit Cape",
    slug: "fringed-knit-cape",
    category: "women",
    price: 168,
    rating: 4.6,
    reviewCount: 54,
    images: [
      img("photo-1434389677669-e08b4cac3105"),
      img("photo-1509319117193-57bab727e09d"),
      img("photo-1556905055-8f358a7a47b2"),
    ],
    description:
      "An open-stitch cape in undyed alpaca with a hand-knotted fringe. Weightless on, warm out of proportion to how little it weighs.",
    details: [
      "Undyed baby alpaca blend",
      "Hand-knotted fringe",
      "Open V-neck, one size",
    ],
    specifications: {
      Material: "70% baby alpaca, 30% merino",
      Weight: "310 g",
      Fit: "One size",
      Origin: "Made in Peru",
      Care: "Hand wash cold, dry flat",
    },
    sizes: ONE_SIZE,
    colors: [{ name: "Ecru", hex: "#e8dfcd" }],
    tags: ["knitwear", "alpaca"],
    inStock: true,
  },
  {
    id: "2003",
    name: "Utility Cargo Trouser",
    slug: "utility-cargo-trouser",
    category: "women",
    price: 132,
    originalPrice: 168,
    rating: 4.4,
    reviewCount: 112,
    images: [
      img("photo-1594633312681-425c7b97ccd1"),
      img("photo-1517445312882-bc9910d016b7"),
      img("photo-1515886657613-9f3515b0c78f"),
    ],
    description:
      "A tapered cargo in washed Tencel twill that drapes instead of stiffening. Elasticated back waist, and pockets sized for a phone.",
    details: [
      "Washed Tencel-cotton twill",
      "Elasticated back waistband",
      "Bellowed cargo pockets with a hidden snap",
    ],
    specifications: {
      Material: "62% Tencel, 38% cotton",
      Rise: "Mid",
      Inseam: "72 cm",
      Origin: "Made in Portugal",
      Care: "Machine wash cold",
    },
    sizes: APPAREL_SIZES,
    colors: [
      { name: "Blush", hex: "#d8a79b" },
      { name: "Black", hex: "#1c1c1c" },
    ],
    tags: ["trousers", "utility"],
    featured: true,
    inStock: true,
  },
  {
    id: "2004",
    name: "Colourblock Track Set",
    slug: "colourblock-track-set",
    category: "women",
    price: 178,
    rating: 4.3,
    reviewCount: 68,
    images: [
      img("photo-1515886657613-9f3515b0c78f"),
      img("photo-1620799140188-3b2a02fd9a77"),
      img("photo-1594633312681-425c7b97ccd1"),
    ],
    description:
      "Cropped hoodie and matching jogger in a brushed-back cotton loopback. Sold as a set, styled apart just as happily.",
    details: [
      "Brushed-back cotton loopback",
      "Cropped hoodie with a kangaroo pocket",
      "Tapered jogger with a drawcord waist",
    ],
    specifications: {
      Material: "100% organic cotton",
      Weight: "340 gsm",
      Fit: "Relaxed",
      Origin: "Made in Turkey",
      Care: "Machine wash cold",
    },
    sizes: APPAREL_SIZES,
    colors: [
      { name: "Saffron", hex: "#e3a81b" },
      { name: "Stone", hex: "#cfc6b8" },
    ],
    tags: ["loungewear", "set"],
    newArrival: true,
    inStock: true,
  },
  {
    id: "2005",
    name: "Pleated Wide-Leg Trouser",
    slug: "pleated-wide-leg-trouser",
    category: "women",
    price: 148,
    rating: 4.7,
    reviewCount: 94,
    images: [
      img("photo-1517445312882-bc9910d016b7"),
      img("photo-1509319117193-57bab727e09d"),
      img("photo-1594633312681-425c7b97ccd1"),
    ],
    description:
      "A high-rise trouser with a single forward pleat and a leg that falls straight from the hip. The one that makes everything else in the wardrobe work harder.",
    details: [
      "Single forward pleat, high rise",
      "Wool-blend suiting with a matte finish",
      "Hook-and-bar closure with a hidden extension",
    ],
    specifications: {
      Material: "78% wool, 22% viscose",
      Rise: "High",
      Inseam: "78 cm",
      Origin: "Made in Portugal",
      Care: "Dry clean recommended",
    },
    sizes: APPAREL_SIZES,
    colors: [
      { name: "Oat", hex: "#d6c8ab" },
      { name: "Charcoal", hex: "#3e3e3e" },
    ],
    tags: ["trousers", "tailoring"],
    featured: true,
    inStock: true,
  },
  {
    id: "2006",
    name: "Relaxed Graphic Tee",
    slug: "relaxed-graphic-tee",
    category: "women",
    price: 42,
    originalPrice: 58,
    rating: 4.1,
    reviewCount: 143,
    images: [
      img("photo-1554568218-0f1715e72254"),
      img("photo-1576566588028-4147f3842f27"),
      img("photo-1581655353564-df123a1eb820"),
    ],
    description:
      "An oversized tee with a softly faded screen print, cut long enough to knot at the waist or leave to hang.",
    details: [
      "Soft-hand screen print",
      "Oversized body with dropped shoulders",
      "Ringspun cotton jersey",
    ],
    specifications: {
      Material: "100% ringspun cotton",
      Weight: "170 gsm",
      Fit: "Oversized",
      Origin: "Made in Portugal",
      Care: "Wash inside out, cold",
    },
    sizes: APPAREL_SIZES,
    colors: [
      { name: "White", hex: "#f6f5f2" },
      { name: "Washed Black", hex: "#33312f" },
    ],
    tags: ["print", "cotton"],
    inStock: true,
  },
  {
    id: "2007",
    name: "Ribbed Merino Knit",
    slug: "ribbed-merino-knit",
    category: "women",
    price: 156,
    rating: 4.8,
    reviewCount: 77,
    images: [
      img("photo-1556905055-8f358a7a47b2"),
      img("photo-1509319117193-57bab727e09d"),
      img("photo-1434389677669-e08b4cac3105"),
    ],
    description:
      "A fine-gauge merino rib that skims rather than clings. Fully fashioned, so the seams follow the body instead of cutting across it.",
    details: [
      "Fine-gauge extra-fine merino",
      "Fully fashioned shoulders",
      "Mock neck with a rolled edge",
    ],
    specifications: {
      Material: "100% extra-fine merino wool",
      Gauge: "14 gg",
      Fit: "Slim",
      Origin: "Made in Italy",
      Care: "Hand wash cold, dry flat",
    },
    sizes: APPAREL_SIZES,
    colors: [
      { name: "Rust", hex: "#b1603a" },
      { name: "Fog", hex: "#b9bbb5" },
    ],
    tags: ["knitwear", "merino"],
    newArrival: true,
    inStock: true,
  },
  {
    id: "2008",
    name: "Classic Straight Jean",
    slug: "classic-straight-jean",
    category: "women",
    price: 125,
    rating: 4.5,
    reviewCount: 203,
    images: [
      img("photo-1516762689617-e1cffcef479d"),
      img("photo-1525507119028-ed4c629a60a3"),
      img("photo-1556905055-8f358a7a47b2"),
    ],
    description:
      "Rigid Japanese selvedge with just enough stretch to sit down in. A true straight leg that breaks cleanly over a boot.",
    details: [
      "12.5oz Japanese selvedge denim",
      "Mid rise, true straight leg",
      "Copper rivets and a chain-stitched hem",
    ],
    specifications: {
      Material: "98% cotton, 2% elastane",
      Weight: "12.5 oz",
      Rise: "Mid",
      Origin: "Made in Japan",
      Care: "Wash sparingly, inside out",
    },
    sizes: APPAREL_SIZES,
    colors: [
      { name: "Mid Indigo", hex: "#43628a" },
      { name: "Ecru", hex: "#e4ded1" },
    ],
    tags: ["denim", "selvedge"],
    inStock: true,
  },
  {
    id: "2009",
    name: "Printed Stiletto Pump",
    slug: "printed-stiletto-pump",
    category: "women",
    price: 225,
    originalPrice: 310,
    rating: 4.2,
    reviewCount: 41,
    images: [
      img("photo-1543163521-1bf539c55dd2"),
      img("photo-1595950653106-6c9ebd614d3a"),
      img("photo-1608667508764-33cf0726b13a"),
    ],
    description:
      "A pointed pump in printed satin on a 90mm heel, with a padded leather footbed that makes the evening survivable.",
    details: [
      "Digitally printed satin upper",
      "90 mm covered heel",
      "Padded nappa leather footbed",
    ],
    specifications: {
      Material: "Printed satin",
      "Heel height": "90 mm",
      Sole: "Leather with rubber tap",
      Origin: "Made in Italy",
      Care: "Store with shoe trees",
    },
    sizes: SHOE_SIZES,
    colors: [{ name: "Azure Print", hex: "#2f7fb5" }],
    tags: ["footwear", "occasion"],
    inStock: false,
  },
  {
    id: "2010",
    name: "Blush Runner Sneaker",
    slug: "blush-runner-sneaker",
    category: "women",
    price: 138,
    rating: 4.4,
    reviewCount: 119,
    images: [
      img("photo-1608667508764-33cf0726b13a"),
      img("photo-1595950653106-6c9ebd614d3a"),
      img("photo-1600185365483-26d7a4cc7519"),
    ],
    description:
      "A chunky-soled runner in tonal blush suede and mesh. Sculpted enough to read as deliberate, cushioned enough for a full day.",
    details: [
      "Suede and breathable mesh upper",
      "Sculpted EVA midsole",
      "Moulded heel counter",
    ],
    specifications: {
      Material: "Suede and mesh",
      Sole: "EVA and rubber",
      Fit: "Size up half",
      Origin: "Made in Vietnam",
      Care: "Spot clean",
    },
    sizes: SHOE_SIZES,
    colors: [
      { name: "Blush", hex: "#e0b7ad" },
      { name: "Pastel Mix", hex: "#cbd8e6" },
    ],
    tags: ["footwear", "sneaker"],
    featured: true,
    inStock: true,
  },
  {
    id: "2011",
    name: "Pastel Court Sneaker",
    slug: "pastel-court-sneaker",
    category: "women",
    price: 128,
    originalPrice: 160,
    rating: 4.6,
    reviewCount: 158,
    images: [
      img("photo-1595950653106-6c9ebd614d3a"),
      img("photo-1608667508764-33cf0726b13a"),
      img("photo-1611652022419-a9419f74343d"),
    ],
    description:
      "The court silhouette rebuilt in soft pastel leather, with a slightly raised platform sole that adds height without bulk.",
    details: [
      "Soft nappa leather upper",
      "Raised platform cupsole",
      "Recycled laces and lining",
    ],
    specifications: {
      Material: "Nappa leather",
      Sole: "Rubber platform",
      Fit: "True to size",
      Origin: "Made in Portugal",
      Care: "Wipe with a damp cloth",
    },
    sizes: SHOE_SIZES,
    colors: [
      { name: "Pastel Mix", hex: "#e9dcea" },
      { name: "White", hex: "#f4f2ee" },
    ],
    tags: ["footwear", "sneaker"],
    newArrival: true,
    inStock: true,
  },
  {
    id: "2012",
    name: "Cable Knit Cardigan",
    slug: "cable-knit-cardigan",
    category: "women",
    price: 195,
    rating: 4.7,
    reviewCount: 62,
    images: [
      img("photo-1509319117193-57bab727e09d"),
      img("photo-1445205170230-053b83016050"),
      img("photo-1434389677669-e08b4cac3105"),
    ],
    description:
      "A hand-framed cable cardigan in lambswool, with horn buttons and a body long enough to wear as a light coat.",
    details: [
      "Hand-framed lambswool cable knit",
      "Natural horn buttons",
      "Longline body with side vents",
    ],
    specifications: {
      Material: "100% lambswool",
      Gauge: "5 gg",
      Fit: "Relaxed",
      Origin: "Made in Scotland",
      Care: "Hand wash cold, dry flat",
    },
    sizes: APPAREL_SIZES,
    colors: [
      { name: "Oatmeal", hex: "#ded2bd" },
      { name: "Moss", hex: "#767a5f" },
    ],
    tags: ["knitwear", "lambswool", "premium"],
    inStock: true,
  },
  {
    id: "3001",
    name: "Studio Wireless Headphones",
    slug: "studio-wireless-headphones",
    category: "accessories",
    price: 289,
    originalPrice: 349,
    rating: 4.8,
    reviewCount: 412,
    images: [
      img("photo-1505740420928-5e560c06d30e"),
      img("photo-1546868871-7041f2a55e12"),
      img("photo-1523275335684-37898b6baf30"),
    ],
    description:
      "Over-ear headphones with adaptive noise cancellation, memory-foam earcups and a battery that outlasts a long-haul flight twice over.",
    details: [
      "Adaptive hybrid noise cancellation",
      "40 mm dynamic drivers",
      "60-hour battery, USB-C fast charge",
    ],
    specifications: {
      Drivers: "40 mm dynamic",
      Battery: "60 hours (ANC on)",
      Connectivity: "Bluetooth 5.3, USB-C, 3.5 mm",
      Weight: "254 g",
      "In the box": "Headphones, case, cables",
    },
    colors: [
      { name: "Black", hex: "#1d1d1d" },
      { name: "Sand", hex: "#d9cfc0" },
    ],
    tags: ["audio", "tech"],
    featured: true,
    inStock: true,
  },
  {
    id: "3002",
    name: "Chronograph Leather Watch",
    slug: "chronograph-leather-watch",
    category: "accessories",
    price: 340,
    rating: 4.6,
    reviewCount: 128,
    images: [
      img("photo-1622434641406-a158123450f9"),
      img("photo-1620625515032-6ed0c1790c75"),
      img("photo-1523170335258-f5ed11844a49"),
    ],
    description:
      "A 41mm chronograph with a sunray dial and an oiled leather strap that darkens with wear. Sapphire crystal, 50m water resistance.",
    details: [
      "41 mm stainless steel case",
      "Sapphire crystal with anti-reflective coating",
      "Italian oiled leather strap, quick release",
    ],
    specifications: {
      "Case size": "41 mm",
      Movement: "Japanese quartz chronograph",
      "Water resistance": "50 m",
      Crystal: "Sapphire",
      Strap: "Italian leather, 20 mm",
    },
    colors: [
      { name: "Espresso", hex: "#503523" },
      { name: "Black", hex: "#222222" },
    ],
    tags: ["watch", "leather"],
    featured: true,
    inStock: true,
  },
  {
    id: "3003",
    name: "Steel Dive Watch",
    slug: "steel-dive-watch",
    category: "accessories",
    price: 495,
    originalPrice: 620,
    rating: 4.9,
    reviewCount: 87,
    images: [
      img("photo-1523170335258-f5ed11844a49"),
      img("photo-1620625515032-6ed0c1790c75"),
      img("photo-1584917865442-de89df76afd3"),
    ],
    description:
      "An automatic diver with a 120-click unidirectional bezel and a bracelet that tapers properly toward the clasp. 300m rated.",
    details: [
      "Automatic movement, 40-hour reserve",
      "120-click unidirectional ceramic bezel",
      "Solid-link bracelet with a dive extension",
    ],
    specifications: {
      "Case size": "42 mm",
      Movement: "Automatic, 40 h reserve",
      "Water resistance": "300 m",
      Crystal: "Sapphire",
      Bracelet: "Stainless steel, 22 mm",
    },
    colors: [{ name: "Steel / Navy", hex: "#2c3e5c" }],
    tags: ["watch", "automatic", "premium"],
    inStock: true,
  },
  {
    id: "3004",
    name: "Minimal Smartwatch",
    slug: "minimal-smartwatch",
    category: "accessories",
    price: 259,
    rating: 4.3,
    reviewCount: 234,
    images: [
      img("photo-1523275335684-37898b6baf30"),
      img("photo-1546868871-7041f2a55e12"),
      img("photo-1505740420928-5e560c06d30e"),
    ],
    description:
      "A quietly designed smartwatch with an always-on AMOLED display, seven-day battery and a silicone strap that does not catch on a cuff.",
    details: [
      "1.4-inch always-on AMOLED display",
      "7-day typical battery life",
      "Heart rate, SpO2 and sleep tracking",
    ],
    specifications: {
      Display: "1.4 in AMOLED",
      Battery: "7 days typical",
      "Water resistance": "5 ATM",
      Sensors: "HR, SpO2, accelerometer",
      Strap: "Silicone, 22 mm",
    },
    colors: [
      { name: "White", hex: "#f1f1ef" },
      { name: "Graphite", hex: "#3a3a3c" },
    ],
    tags: ["watch", "tech"],
    newArrival: true,
    inStock: true,
  },
  {
    id: "3005",
    name: "Classic Acetate Sunglasses",
    slug: "classic-acetate-sunglasses",
    category: "accessories",
    price: 185,
    originalPrice: 230,
    rating: 4.7,
    reviewCount: 176,
    images: [
      img("photo-1572635196237-14b3f281503f"),
      img("photo-1469334031218-e382a71b716b"),
      img("photo-1479064555552-3ef4979f8908"),
    ],
    description:
      "Hand-polished Italian acetate in the shape that has outlived every trend since. Polarised CR-39 lenses, pinned metal hinges.",
    details: [
      "Hand-polished Mazzucchelli acetate",
      "Polarised CR-39 lenses, 100% UV400",
      "Five-barrel pinned hinges",
    ],
    specifications: {
      Frame: "Italian acetate",
      Lens: "Polarised CR-39, UV400",
      "Lens width": "52 mm",
      Origin: "Made in Italy",
      "In the box": "Case and cloth",
    },
    colors: [
      { name: "Black", hex: "#1a1a1a" },
      { name: "Tortoise", hex: "#7a4f28" },
    ],
    tags: ["eyewear", "polarised"],
    featured: true,
    inStock: true,
  },
  {
    id: "3006",
    name: "Structured Leather Handbag",
    slug: "structured-leather-handbag",
    category: "accessories",
    price: 395,
    rating: 4.8,
    reviewCount: 73,
    images: [
      img("photo-1584917865442-de89df76afd3"),
      img("photo-1587467512961-120760940315"),
      img("photo-1591561954557-26941169b49e"),
    ],
    description:
      "A top-handle bag in saffiano calf with a palladium turn-lock. Rigid enough to stand on its own, light enough to carry all day.",
    details: [
      "Saffiano calf leather",
      "Palladium-finish turn-lock",
      "Detachable shoulder strap",
    ],
    specifications: {
      Material: "Saffiano calf leather",
      Dimensions: "26 x 19 x 11 cm",
      Hardware: "Palladium finish",
      Lining: "Suede",
      Origin: "Made in Italy",
    },
    colors: [
      { name: "Scarlet", hex: "#c0392b" },
      { name: "Black", hex: "#1e1e1e" },
    ],
    tags: ["bag", "leather", "premium"],
    featured: true,
    inStock: true,
  },
  {
    id: "3007",
    name: "Quilted Chain Shoulder Bag",
    slug: "quilted-chain-shoulder-bag",
    category: "accessories",
    price: 310,
    originalPrice: 385,
    rating: 4.5,
    reviewCount: 58,
    images: [
      img("photo-1587467512961-120760940315"),
      img("photo-1584917865442-de89df76afd3"),
      img("photo-1591561954557-26941169b49e"),
    ],
    description:
      "Diamond-quilted lambskin on a gold chain that can be doubled to wear short. Slim enough to disappear under a coat.",
    details: [
      "Diamond-quilted lambskin",
      "Doubling gold-tone chain strap",
      "Interior card slots",
    ],
    specifications: {
      Material: "Quilted lambskin",
      Dimensions: "23 x 14 x 7 cm",
      Hardware: "Gold tone",
      Lining: "Grosgrain",
      Origin: "Made in Italy",
    },
    colors: [{ name: "Scarlet", hex: "#b5271f" }],
    tags: ["bag", "leather", "evening"],
    inStock: true,
  },
  {
    id: "3008",
    name: "Printed Canvas Tote",
    slug: "printed-canvas-tote",
    category: "accessories",
    price: 145,
    rating: 4.2,
    reviewCount: 96,
    images: [
      img("photo-1591561954557-26941169b49e"),
      img("photo-1587467512961-120760940315"),
      img("photo-1584917865442-de89df76afd3"),
    ],
    description:
      "A roomy tote in coated canvas with a hand-drawn floral print and leather handles that soften with use.",
    details: [
      "Water-resistant coated canvas",
      "Vegetable-tanned leather handles",
      "Interior zip pocket",
    ],
    specifications: {
      Material: "Coated canvas and leather",
      Dimensions: "34 x 28 x 14 cm",
      Hardware: "Antique brass",
      Lining: "Cotton twill",
      Origin: "Made in Portugal",
    },
    colors: [{ name: "Floral", hex: "#c98a7a" }],
    tags: ["bag", "canvas"],
    inStock: true,
  },
  {
    id: "3009",
    name: "Commuter Backpack",
    slug: "commuter-backpack",
    category: "accessories",
    price: 175,
    rating: 4.6,
    reviewCount: 189,
    images: [
      img("photo-1553062407-98eeb64c6a62"),
      img("photo-1547949003-9792a18a2601"),
      img("photo-1591561954557-26941169b49e"),
    ],
    description:
      "A clean-lined pack in recycled ballistic nylon with a padded 16-inch laptop sleeve and a luggage pass-through.",
    details: [
      "Recycled ballistic nylon with a DWR finish",
      "Padded 16-inch laptop compartment",
      "Luggage pass-through and hidden security pocket",
    ],
    specifications: {
      Material: "Recycled ballistic nylon",
      Capacity: "22 L",
      "Laptop fit": "Up to 16 in",
      Weight: "980 g",
      Origin: "Made in Vietnam",
    },
    colors: [
      { name: "Navy", hex: "#22293c" },
      { name: "Black", hex: "#1c1c1c" },
    ],
    tags: ["bag", "travel"],
    inStock: true,
  },
  {
    id: "3010",
    name: "Weekend Rucksack",
    slug: "weekend-rucksack",
    category: "accessories",
    price: 220,
    originalPrice: 275,
    rating: 4.7,
    reviewCount: 104,
    images: [
      img("photo-1547949003-9792a18a2601"),
      img("photo-1553062407-98eeb64c6a62"),
      img("photo-1591561954557-26941169b49e"),
    ],
    description:
      "A roll-top rucksack in waxed canvas with full-grain leather straps. Built for two nights away and a decade of them.",
    details: [
      "18oz waxed cotton canvas",
      "Full-grain leather straps and base",
      "Roll-top closure with side compression",
    ],
    specifications: {
      Material: "Waxed canvas and leather",
      Capacity: "28 L",
      "Laptop fit": "Up to 15 in",
      Weight: "1.4 kg",
      Origin: "Made in Portugal",
    },
    colors: [
      { name: "Slate", hex: "#4b5147" },
      { name: "Tan", hex: "#9b6b42" },
    ],
    tags: ["bag", "travel", "waxed-canvas"],
    newArrival: true,
    inStock: true,
  },
  {
    id: "3011",
    name: "Layered Gold Necklace",
    slug: "layered-gold-necklace",
    category: "accessories",
    price: 165,
    rating: 4.7,
    reviewCount: 142,
    images: [
      img("photo-1611652022419-a9419f74343d"),
      img("photo-1611085583191-a3b181a88401"),
      img("photo-1608042314453-ae338d80c427"),
    ],
    description:
      "Two chains of different gauges on a single clasp, so the layering stays where you put it. 14k gold vermeil over recycled silver.",
    details: [
      "14k gold vermeil over recycled sterling silver",
      "Dual-chain single clasp",
      "Adjustable 40-45 cm",
    ],
    specifications: {
      Material: "14k gold vermeil",
      Length: "40-45 cm adjustable",
      Clasp: "Lobster",
      Origin: "Made in Thailand",
      Care: "Remove before swimming",
    },
    colors: [{ name: "Gold", hex: "#c9a227" }],
    tags: ["jewellery", "gold"],
    featured: true,
    inStock: true,
  },
  {
    id: "3012",
    name: "Pearl Pendant Necklace",
    slug: "pearl-pendant-necklace",
    category: "accessories",
    price: 132,
    rating: 4.5,
    reviewCount: 88,
    images: [
      img("photo-1611085583191-a3b181a88401"),
      img("photo-1611652022419-a9419f74343d"),
      img("photo-1608042314453-ae338d80c427"),
    ],
    description:
      "A single freshwater pearl on a fine cable chain. Quiet enough for every day, formal enough for the evening it turns into.",
    details: [
      "8 mm freshwater cultured pearl",
      "Fine cable chain in gold vermeil",
      "Adjustable 42-47 cm",
    ],
    specifications: {
      Material: "Freshwater pearl, gold vermeil",
      "Pearl size": "8 mm",
      Length: "42-47 cm adjustable",
      Clasp: "Spring ring",
      Care: "Wipe with a soft cloth",
    },
    colors: [{ name: "Pearl / Gold", hex: "#e6dfd2" }],
    tags: ["jewellery", "pearl"],
    newArrival: true,
    inStock: true,
  },
  {
    id: "3013",
    name: "Stone Signet Ring Set",
    slug: "stone-signet-ring-set",
    category: "accessories",
    price: 118,
    originalPrice: 148,
    rating: 4.4,
    reviewCount: 67,
    images: [
      img("photo-1608042314453-ae338d80c427"),
      img("photo-1611085583191-a3b181a88401"),
      img("photo-1611652022419-a9419f74343d"),
    ],
    description:
      "Three stacking rings set with amazonite, carnelian and a plain gold band. Wear them together or break the set apart.",
    details: [
      "Set of three stacking rings",
      "Amazonite and carnelian cabochons",
      "14k gold vermeil bands",
    ],
    specifications: {
      Material: "Gold vermeil, natural stone",
      Sizes: "US 6, 7, 8",
      Stones: "Amazonite, carnelian",
      Origin: "Made in Thailand",
      Care: "Avoid contact with perfume",
    },
    colors: [{ name: "Gold / Stone", hex: "#c9a227" }],
    tags: ["jewellery", "set"],
    inStock: true,
  },
  {
    id: "3014",
    name: "Panama Straw Hat",
    slug: "panama-straw-hat",
    category: "accessories",
    price: 95,
    rating: 4.3,
    reviewCount: 54,
    images: [
      img("photo-1533827432537-70133748f5c8"),
      img("photo-1556306535-0f09a537f0a3"),
      img("photo-1479064555552-3ef4979f8908"),
    ],
    description:
      "Hand-woven toquilla straw with a grosgrain band. Rolls for travel and springs back into shape.",
    details: [
      "Hand-woven toquilla straw",
      "Grosgrain ribbon band",
      "Rollable, travel-safe crown",
    ],
    specifications: {
      Material: "Toquilla straw",
      Band: "Cotton grosgrain",
      Brim: "7 cm",
      Origin: "Made in Ecuador",
      Care: "Store on the crown",
    },
    sizes: ["S", "M", "L"],
    colors: [{ name: "Natural", hex: "#ddc9a3" }],
    tags: ["hat", "summer"],
    inStock: true,
  },
  {
    id: "3015",
    name: "Wool Blend Cap",
    slug: "wool-blend-cap",
    category: "accessories",
    price: 58,
    rating: 4.1,
    reviewCount: 112,
    images: [
      img("photo-1556306535-0f09a537f0a3"),
      img("photo-1533827432537-70133748f5c8"),
      img("photo-1571945153237-4929e783af4a"),
    ],
    description:
      "A structured six-panel cap in a brushed wool blend with a woven label and a matte snap closure.",
    details: [
      "Brushed wool-blend crown",
      "Structured six-panel construction",
      "Adjustable matte snap closure",
    ],
    specifications: {
      Material: "70% wool, 30% polyester",
      Fit: "Adjustable",
      Brim: "Flat, pre-curved option",
      Origin: "Made in China",
      Care: "Spot clean only",
    },
    sizes: ONE_SIZE,
    colors: [
      { name: "Heather Grey", hex: "#9c9c9a" },
      { name: "Black", hex: "#1f1f1f" },
    ],
    tags: ["hat", "wool"],
    inStock: true,
  },
];

